CREATE TABLE PATIENT(
	PATIENT_ID CHAR(10) PRIMARY KEY,
	PATIENT_NAME VARCHAR(50) NOT NULL,
	PATIENT_ADDRESS VARCHAR(50) NOT NULL,
	CITY_PROV_PC VARCHAR(25) NOT NULL,
	TELEPHONE VARCHAR(15) NOT NULL,
	SEX CHAR(10) NOT NULL,
	HCN VARCHAR(20) NOT NULL,
	EXTENSION VARCHAR(5) NOT NULL,
	DATE_ADMITTED DATE NOT NULL,
	PATIENT_BED_ID CHAR(10) NOT NULL,
	FINANCIAL_STATUS VARCHAR(20) NOT NULL,
	DISCHARGE_DATE DATE NOT NULL
);


CREATE TABLE PHYSICIAN(
	PHYSICIAN_ID CHAR(10) PRIMARY KEY,
	NAME VARCHAR(25) NOT NULL,
	SPECIALITY VARCHAR(50) NOT NULL,
	PHONE VARCHAR (15) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE PATIENT_REPORT(
	REPORT_ID CHAR(10) PRIMARY KEY,
	PATIENT_ID CHAR(10) NOT NULL,
	PHYSICIAN_ID CHAR(10) NOT NULL,
	REPORT_DATE DATE NOT NULL,
	DIAGNOSIS VARCHAR(100) NOT NULL,
	TREATMENT VARCHAR(100) NOT NULL,
	NOTE VARCHAR(100) NOT NULL,
	FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT,
	FOREIGN KEY(PHYSICIAN_ID) REFERENCES PHYSICIAN
);



CREATE TABLE APPOINTMENTS(
	APPOINTMENT_ID CHAR(10) PRIMARY KEY,
	PATIENT_ID CHAR(10) NOT NULL,
	PHYSICIAN_ID CHAR(10) NOT NULL,
	APPOINTMENT_DATE DATE NOT NULL,
	APPOINTMENT_TYPE VARCHAR(25) NOT NULL,
	APPOINTMENT_NOTE VARCHAR(100) NOT NULL,
	FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT
);



CREATE TABLE ROOM(
	ROOM_ID CHAR(10) PRIMARY KEY,
	BED_ID CHAR(10) NOT NULL,
	PATIENT_ID CHAR(10),
	ROOM_NUMBER VARCHAR(10) NOT NULL,
	ROOM_TYPE VARCHAR(25) NOT NULL,
	OCCUPANCY_STATUS VARCHAR(50) NOT NULL,
	FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)

);




CREATE TABLE INVOICE (
	INVOICE_ID CHAR(10) PRIMARY KEY,
	PATIENT_ID CHAR(10) NOT NULL,
	INVOICE_DATE DATE NOT NULL,
	BILL_AMOUNT DECIMAL(10,2) NOT NULL,
	BILL_AMOUNT_PAID DECIMAL(10,2) NOT NULL,
	PAYMENT_METHOD VARCHAR(50) NOT NULL,
	FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT

);


CREATE TABLE PAYMENT(
	PAYMENT_ID CHAR(10) PRIMARY KEY,
	INVOICE_ID CHAR(10) NOT NULL,
	PAYMENT_DATE DATE NOT NULL,
	AMOUNT_PAID DECIMAL(10,2) NOT NULL,
	BILL_AMOUNT_PAID DECIMAL(10,2) NOT NULL,
	PAYMENT_METHOD VARCHAR(50) NOT NULL,
	FOREIGN KEY(INVOICE_ID ) REFERENCES INVOICE(INVOICE_ID )
);


CREATE TABLE COST_CENTRE(
	COST_CENTRE_ID CHAR(10) PRIMARY KEY,
	ITEM_NAME VARCHAR(50) NOT NULL,
	ITEM_DESCRIPTION VARCHAR(100) NOT NULL,
	ITEM_COST DECIMAL(10,2) NOT NULL

);



CREATE TABLE LAB_REPORTS(
	REPORT_ID CHAR(10) PRIMARY KEY,
	PATIENT_ID CHAR(10) NOT NULL,
	REPORT_DETAILS VARCHAR(100) NOT NULL,
	FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);



